add FS function
pkdotson/garageScript pull request #2
Opened 2017-08-15 21:15 UTC by pkdotson

2017-08-15 22:58 UTC, songz commented on Fs.js
> +    console.log(name);
can you write this into a file in your directory?

2017-08-15 23:00 UTC, seemcat approved these changes
Try making it shorter next time! But this works.

2017-08-17 21:53 UTC, SahilKalra98 commented on prntname.txt
> +READMEalopezameybettybharathbillcecilecolindsoperemilyemmanuelgitgitlab-runnerhuejiajiarunkinuelouismadhumadhubmanikmcmikemingoliviapdiddypeterahulsahilsongsyatriyj
Don't commit generated files :)

2017-08-17 22:03 UTC, songz commented on Fs.js
> +  s = s + name;
what is `s`? better variable names please.

2017-08-17 22:04 UTC, allopez7 commented on Fs.js
> +let s = '';
use a more descriptive name for s

2017-08-17 22:13 UTC, allopez7 commented on Fs.js
> +  fs.writeFile('prntname.txt', s, (err) => {
The s was not changed to string here.

2017-08-17 22:13 UTC, allopez7 requested changes
One change required.

2017-08-17 22:14 UTC, songz commented on Fs.js
> +let string = '';
string is a really bad variable name. Let's call it `allNamesWithoutMe`

2017-08-17 22:14 UTC, songz commented on Fs.js
> +const fs = require('fs');
Your file name is `Fs.js`. Please don't capitalize your file name.

2017-08-18 01:39 UTC, songz commented on fs.js
> +  allNamesWithoutMe = allNamesWithoutMe + ' ' + name;
add 2 space!

2017-08-21 23:29 UTC, merged